(function() {var implementors = {};
implementors['jsonrpc_lite'] = ["impl <a class='trait' href='serde_json/value/trait.ToJson.html' title='serde_json::value::ToJson'>ToJson</a> for <a class='enum' href='jsonrpc_lite/enum.Id.html' title='jsonrpc_lite::Id'>Id</a>","impl <a class='trait' href='serde_json/value/trait.ToJson.html' title='serde_json::value::ToJson'>ToJson</a> for <a class='enum' href='jsonrpc_lite/enum.Params.html' title='jsonrpc_lite::Params'>Params</a>","impl <a class='trait' href='serde_json/value/trait.ToJson.html' title='serde_json::value::ToJson'>ToJson</a> for <a class='struct' href='jsonrpc_lite/struct.Error.html' title='jsonrpc_lite::Error'>Error</a>","impl <a class='trait' href='serde_json/value/trait.ToJson.html' title='serde_json::value::ToJson'>ToJson</a> for <a class='struct' href='jsonrpc_lite/struct.JsonRPC.html' title='jsonrpc_lite::JsonRPC'>JsonRPC</a>",];implementors["serde_json"] = [];implementors["jsonrpc_lite"] = ["impl <a class='trait' href='serde_json/value/trait.ToJson.html' title='serde_json::value::ToJson'>ToJson</a> for <a class='enum' href='jsonrpc_lite/enum.Id.html' title='jsonrpc_lite::Id'>Id</a>","impl <a class='trait' href='serde_json/value/trait.ToJson.html' title='serde_json::value::ToJson'>ToJson</a> for <a class='enum' href='jsonrpc_lite/enum.Params.html' title='jsonrpc_lite::Params'>Params</a>","impl <a class='trait' href='serde_json/value/trait.ToJson.html' title='serde_json::value::ToJson'>ToJson</a> for <a class='enum' href='jsonrpc_lite/enum.JsonRPC.html' title='jsonrpc_lite::JsonRPC'>JsonRPC</a>","impl <a class='trait' href='serde_json/value/trait.ToJson.html' title='serde_json::value::ToJson'>ToJson</a> for <a class='struct' href='jsonrpc_lite/struct.Error.html' title='jsonrpc_lite::Error'>Error</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
